//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRFancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class productImage
    {
        public string productId { get; set; }
        public byte[] productImage1 { get; set; }
        public byte[] productImage2 { get; set; }
        public byte[] productImage3 { get; set; }
        public byte[] productImage4 { get; set; }
        public string categoryId { get; set; }
    
        public virtual category category { get; set; }
        public virtual product product { get; set; }
    }
}
