//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRFancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string productId { get; set; }
        public string productName { get; set; }
        public string categoryId { get; set; }
        public Nullable<decimal> sPrice { get; set; }
        public Nullable<decimal> mPrice { get; set; }
        public Nullable<decimal> lPrice { get; set; }
        public Nullable<decimal> vlPrice { get; set; }
        public Nullable<decimal> sRentPrice { get; set; }
        public Nullable<decimal> mRentPrice { get; set; }
        public Nullable<decimal> lRentPrice { get; set; }
        public Nullable<decimal> vlRentPrice { get; set; }
        public string productDesc { get; set; }
    
        public virtual category category { get; set; }
        public virtual productImage productImage { get; set; }
    }
}
