//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRFancy
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string userId { get; set; }
        public string username { get; set; }
        public Nullable<int> roleId { get; set; }
        public string password { get; set; }
    }
}
